# Generated by Django 4.0.4 on 2022-06-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingName', models.TextField(default='', max_length=100)),
                ('address', models.TextField(blank=True, max_length=200)),
                ('lati', models.DecimalField(decimal_places=8, default=None, max_digits=10)),
                ('longi', models.DecimalField(decimal_places=8, default=None, max_digits=10)),
            ],
        ),
    ]
