# Generated by Django 4.0.4 on 2022-06-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.IntegerField()),
                ('designer_name', models.CharField(max_length=30)),
                ('designer_company', models.CharField(max_length=100)),
                ('bid_amount', models.IntegerField()),
                ('bid_desc', models.TextField(max_length=300)),
            ],
        ),
    ]
